services:
  bot:
    container_name: kon
    #image: git.toast-server.net/toast/kon:main
    build: .
    restart: unless-stopped
    depends_on:
      - cache
  cache:
    container_name: kon-redis
    image: redis/redis-stack-server:7.4.0-v0
    restart: unless-stopped
    ports:
      - 37935:6379/tcp

#  db:
#    container_name: kon-database
#    image: postgres:16.4-alpine3.20
#    restart: unless-stopped
#    ports:
#      - 37930:5432/tcp
#    volumes:
#      - /var/lib/docker/volumes/kon-database:/var/lib/postgresql/data:rw
#    environment:
#      TZ: Australia/Sydney
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
