services:
  bot:
    container_name: kon
    #image: 'git.toast-server.net/toast/kon:main'
    build: .
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
  db:
    container_name: kon-database
    image: postgres:16.2-alpine3.19@sha256:20baeb0510ac2612dab79f843309b37c08ad04adc5d75196f700d29f1da43a38
    restart: unless-stopped
    ports:
      - 37930:5432/tcp
    volumes:
      - /var/lib/docker/volumes/kon-database:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
