[package]
name = "kon_repo"
version = "0.1.0"
edition = "2024"

[dependencies]
bb8 = { workspace = true }
bb8-redis = { workspace = true }
kon_tokens = { workspace = true }
tokio = { workspace = true }
